# Generated by Django 4.0 on 2021-12-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='organizer@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant2meetup', to='meetups.Participant'),
        ),
    ]
