# Generated by Django 4.0 on 2021-12-30 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_meetup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 0, 58, 27, 53171)),
        ),
    ]
